### ISSUE TITLE
Alternative download option

### ISSUE THREAD

**Issue by FlorentF9** [DearCaat/CQU-BPDD#1]
Thank you for making this dataset available! However, I was not able to download the data using the Baidu hosting platform - whatever I do, it shows error messages. Could you please provide an alternative way to access the dataset?

**Comment by DearCaat** [comment]
I also want to provide an alternative download option. But i couldn't find the available cloud drive platform - the file size is about 21 GB. Do u have any recommendations？or aliyundrive? If u have the choice, i will try my best to upload the dataset.

**Comment by FlorentF9** [comment]
I could finally download the dataset using the account of a colleague. However it would still be useful to make it more accessible for people outside China.

**Comment by DearCaat** [comment]
I am very sorry for the inconvenience of downloading, and I will continue to look for a suitable cloud platform.
